stages:
  prepare:
    cmd: python generate_synthetic.py
    outs:
      - data/train.csv
  train:
    cmd: python src/train.py
    deps:
      - data/train.csv
      - src/train.py
    outs:
      - models/model.joblib
      