stages:
  ingest:
    cmd: python src/ingest.py
    deps:
      - src/ingest.py
    outs:
      - data/raw.csv

  preprocess:
    cmd: python src/preprocess.py
    deps:
      - src/preprocess.py
      - data/raw.csv
    outs:
      - data/processed.csv

  train:
    cmd: python src/train.py
    deps:
      - src/train.py
      - data/processed.csv
      - params.yaml
    params:
      - train.n_estimators
      - train.random_state
    outs:
      - model.joblib
    metrics:
      - metrics/training_metrics.txt

  evaluate:
    cmd: python src/evaluate.py
    deps:
      - src/evaluate.py
      - model.joblib
    metrics:
      - metrics/evaluation_metrics.txt