# DID NOT WORK - DOCKERFILE DID NOT BUILD THE NEEDED IMAGE - USEFUL INFORMATION
# # docker-image/Dockerfile
# FROM python:3.13-slim
# RUN pip install --no-cache-dir \
#   "dask==2026.1.2" \
#   "distributed==2026.1.2" \
#   "cloudpickle==3.1.2" \
#   "lz4==4.4.5" \
#   "numpy==2.4.1"
# ENTRYPOINT ["dask-worker"]