# NOT NEEDED BECAUSE DOCKERFILE DID NOT WORK TO BUILD THE NEEDED IMAGE - USEFUL INFORMATION
build:
	docker build -t my-dask-image:local .
up:
	docker compose up -d
down:
	docker compose down
show:
	docker ps -a